### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by mcst12345** [Coloryr/AllMusic_Server#18]
希望客户端mod能在设置里增加一个可以去掉左上角歌曲封面、信息的按钮，每次左上角的歌曲信息与封面一出来就疯狂掉帧，60fps直接掉到15fps，有时甚至卡得不能动

**Comment by Yang-qwq** [comment]
你或许应该去https://[github.com](https://github.com/Coloryr/AllMusic_M/issues)/Coloryr/AllMusic_M/issues提issue
